import Head from 'next/head'
import Contact from '../components/about/Contact'
import Blog from '../components/general/Blog'
import About from '../components/home/About'
import Banner from '../components/home/Banner'
import Faq from '../components/home/Faq'
import Features from '../components/home/Features'
import Portfolio from '../components/home/Portfolio'
import Programs from '../components/home/Programs'
import Support from '../components/home/Support'
import Trending from '../components/home/Trending'

export default function Home() {
  return (
    <div className='font-primary'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner />
      
      <main>
        <Features />
        <About />
        {/* <Support /> */}
        <Portfolio />
        <Trending />
        <Faq />
        <Contact />
        <Programs />
        <Blog />
      </main>
    </div>
  )
}
